// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4lkLR9bumW1Jb7FmmZgN5Ry3qZHC5_dE',
    appId: '1:1007875215696:web:8729e8307c771468a01c55',
    messagingSenderId: '1007875215696',
    projectId: 'nesab-26771',
    authDomain: 'nesab-26771.firebaseapp.com',
    storageBucket: 'nesab-26771.firebasestorage.app',
    measurementId: 'G-L81HD2W2M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ptOYMotGuwHxj5e2Vgakk9JdK-6E8DI',
    appId: '1:1007875215696:android:97001eea4a3e4642a01c55',
    messagingSenderId: '1007875215696',
    projectId: 'nesab-26771',
    storageBucket: 'nesab-26771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Fh2I8fWATqvWf6B_DOitKZV9QwhR45E',
    appId: '1:1007875215696:ios:54dc7292ba339476a01c55',
    messagingSenderId: '1007875215696',
    projectId: 'nesab-26771',
    storageBucket: 'nesab-26771.firebasestorage.app',
    androidClientId: '1007875215696-8nu7hnb3m58eaqs7havhbuqarjs43b2t.apps.googleusercontent.com',
    iosClientId: '1007875215696-n8j368odr9a0pa3518pp038o294c1htr.apps.googleusercontent.com',
    iosBundleId: 'sa.nesab.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Fh2I8fWATqvWf6B_DOitKZV9QwhR45E',
    appId: '1:1007875215696:ios:4bb5b2a7b19ff904a01c55',
    messagingSenderId: '1007875215696',
    projectId: 'nesab-26771',
    storageBucket: 'nesab-26771.firebasestorage.app',
    iosClientId:
        '1007875215696-i9jbkkre2s5fthkmdq38t97v5ogckf0f.apps.googleusercontent.com',
    iosBundleId: 'sa.nesab.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4lkLR9bumW1Jb7FmmZgN5Ry3qZHC5_dE',
    appId: '1:1007875215696:web:40b255c2d39cfe56a01c55',
    messagingSenderId: '1007875215696',
    projectId: 'nesab-26771',
    authDomain: 'nesab-26771.firebaseapp.com',
    storageBucket: 'nesab-26771.firebasestorage.app',
    measurementId: 'G-D7EVVT37NL',
  );
}